'use client'

import { ArrowLeft, Download, Printer } from 'lucide-react'
import { useState } from 'react'
import { PreviewArea } from '@/components/preview-area'
import { UploadArea } from '@/components/upload-area'
import { cn } from '@/lib/utils'

export default function Home() {
  const [content, setContent] = useState<string | null>(null)
  const [filename, setFilename] = useState<string>('document.md')
  const [file, setFile] = useState<File | null>(null)

  const handleFileLoaded = (newContent: string, name: string, uploadedFile: File) => {
    setContent(newContent)
    setFilename(name)
    setFile(uploadedFile)
  }

  const handleBack = () => {
    setContent(null)
  }

  const handleExportHTML = async () => {
    if (!content)
      return

    // Fetch local CSS content for inlining
    let githubMarkdownCss = ''
    let highlightCss = ''
    try {
      const [res1, res2] = await Promise.all([
        fetch('/github-markdown-light.min.css'),
        fetch('/github.min.css'),
      ])
      githubMarkdownCss = await res1.text()
      highlightCss = await res2.text()
    }
    catch (e) {
      console.error('Failed to fetch local CSS for export', e)
    }

    // Get the preview HTML and strip interactive-only elements
    const previewEl = document.getElementById('markdown-preview')
    let previewHtml = ''
    // Check if the original content had a TOC
    const hasToc = previewEl?.querySelector('.toc-container') !== null
    if (previewEl) {
      const clone = previewEl.cloneNode(true) as HTMLElement
      // Remove copy buttons, image zoom overlays, and other non-export elements
      clone.querySelectorAll('[data-no-export]').forEach(el => el.remove())
      // Remove the React-rendered TOC (will be regenerated by JS in the export)
      clone.querySelectorAll('.toc-container').forEach(el => el.remove())
      previewHtml = clone.innerHTML
    }

    const htmlContent = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${filename.replace(/\.md$/i, '')}</title>
<style>
${githubMarkdownCss}
${highlightCss}
  body { box-sizing: border-box; min-width: 200px; max-width: 980px; margin: 0 auto; padding: 45px; }
  @media (max-width: 767px) { body { padding: 15px; } }
  @media print {
    body { background: white; }
    * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }
    .export-copy-btn { display: none !important; }
    .toc-container { break-inside: avoid; }
  }
  /* Code copy button */
  .code-block-wrapper { position: relative; }
  .export-copy-btn {
    position: absolute; right: 8px; top: 8px;
    width: 32px; height: 32px;
    display: flex; align-items: center; justify-content: center;
    border-radius: 6px; border: 1px solid #e5e7eb;
    background: rgba(255,255,255,0.9); cursor: pointer;
    color: #6b7280; line-height: 1;
    backdrop-filter: blur(4px); -webkit-backdrop-filter: blur(4px);
  }
  .export-copy-btn:hover { background: #f3f4f6; }
  /* Image zoom overlay */
  .img-zoom-overlay {
    display: none; position: fixed; inset: 0; z-index: 9999;
    background: rgba(0,0,0,0.7); backdrop-filter: blur(4px); -webkit-backdrop-filter: blur(4px);
    justify-content: center; align-items: center; cursor: pointer;
  }
  .img-zoom-overlay.active { display: flex; }
  .img-zoom-overlay img {
    max-height: 90vh; max-width: 90vw;
    border-radius: 8px; object-fit: contain;
    box-shadow: 0 25px 50px -12px rgba(0,0,0,0.25);
  }
  .markdown-body img { cursor: zoom-in; }
  /* Table of contents */
  .toc-container {
    margin-bottom: 24px; border-radius: 8px;
    border: 1px solid #e5e7eb; background: rgba(249,250,251,0.5);
  }
  .toc-toggle {
    display: flex; width: 100%; align-items: center; gap: 8px;
    padding: 12px 16px; text-align: left; font-size: 14px;
    font-weight: 500; color: #374151; background: none; border: none;
    cursor: pointer; border-radius: 8px;
  }
  .toc-toggle:hover { background: rgba(243,244,246,0.5); }
  .toc-toggle .toc-chevron {
    margin-left: auto; width: 16px; height: 16px; color: #9ca3af;
  }
  .toc-toggle.expanded .toc-chevron { transform: rotate(180deg); }
  .toc-nav { border-top: 1px solid #e5e7eb; padding: 12px 16px; }
  .toc-nav ul { list-style: none; padding: 0; margin: 0; }
  .toc-nav li { margin: 2px 0; }
  .toc-nav a {
    display: block; padding: 4px 8px; font-size: 14px; color: #4b5563;
    text-decoration: none !important; border-radius: 4px; overflow: hidden;
    text-overflow: ellipsis; white-space: nowrap;
  }
  .toc-nav a:hover { background: rgba(229,231,235,0.6); color: #111827; }
</style>
</head>
<body>
<div class="markdown-body">
${previewHtml}
</div>
<script>
(function() {
  var copySvg = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>';
  var checkSvg = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#22c55e" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>';
  var listSvg = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="flex-shrink:0;color:#6b7280"><line x1="8" x2="21" y1="6" y2="6"/><line x1="8" x2="21" y1="12" y2="12"/><line x1="8" x2="21" y1="18" y2="18"/><line x1="3" x2="3.01" y1="6" y2="6"/><line x1="3" x2="3.01" y1="12" y2="12"/><line x1="3" x2="3.01" y1="18" y2="18"/></svg>';
  var chevronSvg = '<svg class="toc-chevron" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg>';

  /* Code copy buttons */
  document.querySelectorAll('.code-block-wrapper').forEach(function(wrapper) {
    var btn = document.createElement('button');
    btn.className = 'export-copy-btn';
    btn.innerHTML = copySvg;
    btn.title = '复制代码';
    btn.addEventListener('click', function() {
      var code = wrapper.querySelector('code');
      if (code) {
        navigator.clipboard.writeText(code.textContent || '').then(function() {
          btn.innerHTML = checkSvg;
          btn.title = '已复制';
          setTimeout(function() { btn.innerHTML = copySvg; btn.title = '复制代码'; }, 2000);
        });
      }
    });
    wrapper.appendChild(btn);
  });

  /* Image zoom lightbox */
  var overlay = document.createElement('div');
  overlay.className = 'img-zoom-overlay';
  var zoomImg = document.createElement('img');
  overlay.appendChild(zoomImg);
  document.body.appendChild(overlay);
  overlay.addEventListener('click', function() { overlay.classList.remove('active'); });
  document.addEventListener('keydown', function(e) { if (e.key === 'Escape') overlay.classList.remove('active'); });

  document.querySelectorAll('.markdown-body img').forEach(function(img) {
    img.addEventListener('click', function() {
      zoomImg.src = img.src;
      overlay.classList.add('active');
    });
  });

  /* Table of contents */
  var generateToc = ${hasToc};
  if (generateToc) {
    var headings = document.querySelectorAll('.markdown-body h1[id], .markdown-body h2[id], .markdown-body h3[id], .markdown-body h4[id], .markdown-body h5[id], .markdown-body h6[id]');
    if (headings.length >= 2) {
      var levels = [];
      headings.forEach(function(h) { levels.push(parseInt(h.tagName.charAt(1))); });
      var minLevel = Math.min.apply(null, levels);
      var items = '';
      headings.forEach(function(h) {
        var level = parseInt(h.tagName.charAt(1));
        var indent = (level - minLevel) * 16;
        items += '<li style="padding-left:' + indent + 'px"><a href="#' + h.id + '" title="' + h.textContent + '">' + h.textContent + '</a></li>';
      });
      var container = document.createElement('div');
      container.className = 'toc-container';
      container.innerHTML = '<button class="toc-toggle" type="button">' + listSvg + '<span>目录</span>' + chevronSvg + '</button><nav class="toc-nav" style="display:none"><ul>' + items + '</ul></nav>';
      var toggleBtn = container.querySelector('.toc-toggle');
      var nav = container.querySelector('.toc-nav');
      toggleBtn.addEventListener('click', function() {
        var isOpen = nav.style.display !== 'none';
        nav.style.display = isOpen ? 'none' : 'block';
        toggleBtn.classList.toggle('expanded', !isOpen);
      });
      var mdBody = document.querySelector('.markdown-body');
      mdBody.insertBefore(container, mdBody.firstChild);
    }
  }
})();
<\/script>
</body>
</html>`

    const blob = new Blob([htmlContent], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename.replace(/\.(md|txt|markdown)$/i, '.html')
    // Ensure extension is html if regex didn't match (e.g. file has no extension)
    if (!a.download.toLowerCase().endsWith('.html')) {
      a.download += '.html'
    }
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  const handlePrint = () => {
    window.print()
  }

  return (
    <main className="min-h-screen bg-[#f1f2f4] text-gray-900 print:bg-white">
      {!content
        ? (
          <div className="flex min-h-screen flex-col items-center justify-center p-4 sm:p-8">
            <img src="/favicon.svg" alt="Logo" className="h-12 w-12 mt-[-100px]" />
            <h1 className="mb-8 text-2xl font-semibold text-gray-800">
              Markdown 预览导出
            </h1>
            <UploadArea onFileLoaded={handleFileLoaded} defaultFile={file} />
          </div>
        )
        : (
          <div className="mx-auto max-w-4xl print:p-0 print:max-w-none">
            <header className="sticky top-0 z-50 mb-4 flex items-center justify-between border-b border-gray-300 bg-[#f1f2f477] px-6 py-4 backdrop-blur-md print:hidden">
              <div className="flex items-center gap-1">
                <button
                  onClick={handleBack}
                  className="flex h-9 w-9 cursor-pointer items-center justify-center rounded-full hover:bg-gray-200"
                  title="返回"
                >
                  <ArrowLeft className="h-5 w-5" />
                </button>
                <div className="flex items-center gap-1">
                  <img src="/favicon.svg" alt="Logo" className="h-6 w-6" />
                  <h1 className="text-lg font-semibold tracking-tight">MDConv</h1>
                </div>
              </div>
              <div className="flex items-center">
                <button
                  onClick={handleExportHTML}
                  className={cn(
                    'inline-flex cursor-pointer items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
                    'hover:bg-gray-200 h-9 px-2',
                  )}
                >
                  <Download className="mr-1 h-4 w-4" />
                  导出 HTML
                </button>
                <button
                  onClick={handlePrint}
                  className={cn(
                    'inline-flex cursor-pointer items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50',
                    'hover:bg-gray-200 h-9 px-2',
                  )}
                >
                  <Printer className="mr-1 h-4 w-4" />
                  打印 PDF
                </button>
              </div>
            </header>

            <div className="flex flex-col gap-2 px-6 pb-20 sm:px-8">
              <div className="flex items-center print:hidden">
                <h2 className="text-sm font-semibold text-gray-500">预览</h2>
                <span className="text-xs ml-2 text-gray-500">{filename}</span>
              </div>
              <div className="min-h-[600px] rounded-xl border border-gray-300 bg-white p-8 print:border-0 print:p-0">
                <PreviewArea content={content} />
              </div>
            </div>
          </div>
        )}
      <footer className="fixed w-full bottom-0 z-50 mt-4 flex items-center justify-center border-t border-gray-300 bg-[#f1f2f477] px-6 h-8 backdrop-blur-md print:hidden">
        <p className="text-sm text-gray-400">
          &copy;
          {' '}
          {new Date().getFullYear()}
          {' '}
          lianchi
        </p>
      </footer>
    </main>
  )
}
